#!/bin/bash

#
#    Copyright (c) 2012 Christopher Noel Hesse
#                <christopher.hesse_at_htp-tel.de>
#

#
# PLEASE NOTE THAT I ACCEPT NO RESPONSIBILITY FOR ANY DAMAGE OR BRICKS
#

# 
# YOU MAY COPY, MODIFY AND/OR REDISTRIBUTE THIS FILE IF YOU MENTION
# THE AUTHOR ("CHRISTOPHER NOEL HESSE, 2012")
#

wrkdir=`cat .setup.wrkdir`

echo
echo "Cleaning up old *.zips on your transformer's sdcard root directory and all the outdated stuff in your working directory"
echo
adb shell rm /sdcard/*.zip
echo

cd $wrkdir

rm kernelblob.LNX
rm kern.blob
