#!/bin/bash

#
#    Copyright (c) 2012 Christopher Noel Hesse
#                <christopher.hesse_at_htp-tel.de>
#

#
# PLEASE NOTE THAT I ACCEPT NO RESPONSIBILITY FOR ANY DAMAGE OR BRICKS
#

# 
# YOU MAY COPY, MODIFY AND/OR REDISTRIBUTE THIS FILE IF YOU MENTION
# THE AUTHOR ("CHRISTOPHER NOEL HESSE, 2012")
#

wrkdir=`cat .setup.wrkdir`

echo "Creating and refreshing the new Update.zip file ..."
echo

cd $wrkdir

if [ -e kernel_asus.zip ]
then
zip -r kernel_asus kern.blob

elif [ -e kernel_aokp.zip ]
then
zip -r kernel_aokp kern.blob

else echo "No kernel zip found ..."
fi

echo
echo "New Update.zip successfully created !"
