#!/bin/bash

#
#    Copyright (c) 2012 Christopher Noel Hesse
#                <christopher.hesse_at_htp-tel.de>
#

#
# PLEASE NOTE THAT I ACCEPT NO RESPONSIBILITY FOR ANY DAMAGE OR BRICKS
#

# 
# YOU MAY COPY, MODIFY AND/OR REDISTRIBUTE THIS FILE IF YOU MENTION
# THE AUTHOR ("CHRISTOPHER NOEL HESSE, 2012")
#

echo

cd /home/chris/tf101-kernel-harmony

make ARCH=arm CROSS_COMPILE=$CCOMPILER -j`grep 'processor' /proc/cpuinfo | wc -l` clean

echo "making config (evt. again) to ensure .config is used on standalone builds"

cleanup_3g

mkaconfig_3g

if [ \! -e /home/chris/tf101-kernel-harmony/include/linux/pm.c ]
then
cp /home/chris/working_dir/3g/include/pm.c /home/chris/tf101-kernel-harmony/include/linux/
fi
if [ \! -e /home/chris/tf101-kernel-harmony/include/linux/pm.h ]
then
cp /home/chris/working_dir/3g/include/pm.h /home/chris/tf101-kernel-harmony/include/linux/
fi
if [ \! -e /home/chris/tf101-kernel-harmony/include/linux/pm-irq.c ]
then
cp /home/chris/working_dir/3g/include/pm-irq.c /home/chris/tf101-kernel-harmony/include/linux/
fi
if [ \! -e /home/chris/tf101-kernel-harmony/include/linux/prm-irq.h ]
then
cp /home/chris/working_dir/3g/include/pm-irq.h /home/chris/tf101-kernel-harmony/include/linux/
fi
if [ \! -e /home/chris/tf101-kernel-harmony/include/linux/pm-t2.c ]
then
cp /home/chris/working_dir/3g/include/pm-t2.c /home/chris/tf101-kernel-harmony/include/linux/
fi
if [ \! -e /home/chris/tf101-kernel-harmony/linux/pm-t3.c ]
then
cp /home/chris/working_dir/3g/include/pm-t3.c /home/chris/tf101-kernel-harmony/include/linux/
fi

echo
echo "Creating zImage"
echo

cd /home/chris/tf101-kernel-harmony

make ARCH=arm CROSS_COMPILE=$CCOMPILER -j`grep 'processor' /proc/cpuinfo | wc -l`
echo
echo "Creating bootimage and merging with ramdisk"
echo

cd /home/chris/working_dir/3g

mkbootimg --kernel /home/chris/tf101-kernel-harmony/arch/arm/boot/zImage --ramdisk /home/chris/working_dir/3g/ramdisk_3g.cpio.gz -o kernelblob.LNX
echo
echo "creating blob file"
echo
blobpack kern.blob.HEADER kern.blob LNX kernelblob.LNX
echo
#echo "cleaning up 3G special files from mainline"

#rm /home/chris/tf101_kernel_rayman/include/linux/pm.c
#rm /home/chris/tf101_kernel_rayman/include/linux/pm.h
#rm /home/chris/tf101_kernel_rayman/include/linux/pm-irq.c
#rm /home/chris/tf101_kernel_rayman/include/linux/pm-irq.h
#rm /home/chris/tf101_kernel_rayman/include/linux/pm-t2.c
#rm /home/chris/tf101_kernel_rayman/include/linux/pm-t3.c

echo

